name: Update data

on:
  workflow_dispatch:
  # repository_dispatch:
  #   types:
  #     - update_data
  # schedule:
  #   # * is a special character in YAML so you have to quote this string
  #   - cron: '15 8 * * 1-5'

# Cancel any in-flight jobs
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pipenv

      - name: Install dependencies
        run: |
          pip install pipenv
          # pipenv install
          pipenv sync

      - name: Run DVC pipelines
        run: |
          pipenv run dvc --version
          pipenv run dvc update -R working
          pipenv run dvc repro -R scripts

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Data updates
          file_pattern: data src scripts working